export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
  
  export default function AccreditedLayout({ children }: { children: React.ReactNode }) {
    return (
      <div>
          {children}
      </div>
    )
  }
  